### ISSUE TITLE
How do I get detailed code of error?

### ISSUE THREAD

**Issue by Azizbek2727** [amadeus4dev/amadeus-python#114]
## Description

ResponseError contains code, etc. ClientError, and error itself, which is status code, etc. 400 - ClientError

but, in debug mode, i get more detailed error, like this:
`Response
{'body': '{"errors":[{"status":400,"code":4926,"title":"INVALID DATA '
         'RECEIVED","detail":"This location code is unknown"}]}',
 'data': None,
 'headers': <http.client.HTTPMessage object at 0x0000018895192640>,
 'http_response': <HTTPError 400: 'Bad Request'>,
 'parsed': True,
 'request': <amadeus.client.request.Request object at 0x0000018895192220>,
 'result': {'errors': [{'code': 4926,
                        'detail': 'This location code is unknown',
                        'status': 400,
                        'title': 'INVALID DATA RECEIVED'}]},
 'status_code': 400}
`
how do i get its code(4926, in the example above) and detail, title, and handle it?

**Comment by tsolakoua** [comment]
For the explanation, I use a 404 error I produced but the same applies to the rest of the errors. 

If you log the `error.response.body` you will get the raw response of the error, as a string.
```
{"errors":[{"status":404,"code":404,"title":"NOT FOUND","detail":"No results matching the query","source":{"parameter":"id","example":"Q930111419"}}],"data":{"self":{}}}
```
If you log the `error.response.result` you will get the. body parsed as JSON
```
{'errors': [{'status': 404, 'code': 404, 'title': 'NOT FOUND', 'detail': 'No results matching the query', 'source': {'parameter': 'id', 'example': 'Q930111419'}}], 'data': {'self': {}}}
```
Then you can parse the error and take specific fields, for example, you can access the detail with as 
`error.response.result['errors'][0]['detail']`
```
No results matching the query
```

The same logic applies to get the title and other fields as well.
