### ISSUE TITLE
Add support for Travel Restrictions API 

### ISSUE THREAD

**Issue by tsolakoua** [amadeus4dev/amadeus-python#119]

**Comment by ozeliger** [comment]
When will this be added?

**Comment by tsolakoua** [comment]
We don't have a specific date to commit right now of when this will be added. However, as described in the readme, you can make any arbitrary API call directly with the `.get` method for endpoints that are not supported yet. For example, for travel restrictions you can do: 

`amadeus.get('/v1/duty-of-care/diseases/covid19-area-report', countryCode='ES')`
