### ISSUE TITLE
Flight data not showing after a specific month

### ISSUE THREAD

**Issue by ankitoscar** [amadeus4dev/amadeus-python#124]
## Description

Hi @tsolakoua, I am using the [Amadues Python SDK](https://github.com/amadeus4dev/amadeus-python) to create a flight data dashboard. I was try to use the functions to get [most booked](https://github.com/amadeus4dev/amadeus-code-examples/blob/master/flight_most_booked_destinations/v1/get/Python%20SDK/flight_most_booked_destinations.py) and [most travelled](https://github.com/amadeus4dev/amadeus-code-examples/blob/master/flight_most_traveled_destinations/v1/get/Python%20SDK/flight_most_traveled_destinations.py) destinations, but no results are coming after `2018-03'. Can you please look into it?

## Steps to Reproduce

1.  Run `pip install amadeus` in your terminal 
2. Run the scripts mentioned in the description with valid credentials
3.  Enter dates in parameter after `2018-03`

__Expected Behavior:__ Get the required data till present month

__Actual Behavior:__ Data available only after `2018-03`

__Stable Behavior?__ All the time

## Versions

What version of Python/Pip are you running? What Operating System are you on?
* Python 3.9.7
* Amadues 5.1.0
* OS - Windows 10
* pip 21.2.3

## Checklist

Please make sure you checked the following:

- Which version of Python are you using? - Yes
- Did you download the latest version of this package? - Yes

**Comment by tsolakoua** [comment]
Hello @ankitoscar, please check the details in this issue https://github.com/amadeus4dev/amadeus-code-examples/issues/17
