### ISSUE TITLE
Requests to the `hotel-offers` API fails with 401

### ISSUE THREAD

**Issue by vladisa88** [amadeus4dev/amadeus-python#141]
## Description

Request to the `/v2/shopping/hotel-offers` fails with 401 error.

## My code snippet

```python3

client = Client(
    client_id='some api key',
    client_secret='some api secret'
)

client.shopping.hotel_offers.get(cityCode='LON')
```

__Expected Behavior:__ I expect normal API call with valid response.

__Actual Behavior:__ `amadeus.client.errors.AuthenticationError: [401]`

## Versions

I use python3.9 and latest version of Amadeus client

The main point is the fact that this code snippet works great.

```python3

client = Client(
    client_id='some api key',
    client_secret='some api secret'
)

client.shopping.flight_offers_search.get(originLocationCode='LON', destinationLocationCode='LIS', departureDate='2022-10-04', adults=1)
```

**Comment by nkilm** [comment]
You did NOT provide correct API_KEY or API_SECRET to Client(). Generate new set of keys and check again.

For me it's working fine.
```python
from amadeus import Client, ResponseError
from dotenv import load_dotenv
from os import environ
from requests import get

load_dotenv()

try:
  amadeus = Client(
      client_id=environ.get("API_KEY"),
      client_secret=environ.get("API_SECRET")
)

except Exception as e:
  print("Hint: Add API Key and API Secret to class Client")
  exit(1)

res = amadeus.shopping.hotel_offers.get(cityCode='LON')
print(res)
```
`output`
![image](https://user-images.githubusercontent.com/79012023/166121671-b81d772b-896f-42de-82bd-105996718dc3.png)


Similarly we can use the API directly also using `requests`. E.g,
```python
URL = "https://test.api.amadeus.com/v3/shopping/hotel-offers?hotelIds=MCLONGHM&adults=1&checkInDate=2022-11-22&roomQuantity=1&paymentPolicy=NONE&bestRateOnly=true"

headers = {}
headers["Accept"] = "application/json"
headers["Authorization"] = "Bearer " + environ.get("AUTH")

response = get(URL,headers = headers)

results= response.json()

for item in results.items():
    print(item)
```
`NOTE: Token should be generated every 30 min in the above case`
