### ISSUE TITLE
Add support of Travel Restrictions V2

### ISSUE THREAD

**Issue by gimperial** [amadeus4dev/amadeus-python#164]

**Comment by siddydutta** [comment]
@gimperial will this replace the v1 implementation?
https://github.com/amadeus4dev/amadeus-python/blob/82f1af83405a9d65d0a83a06ebe6c9029543ca9c/amadeus/duty_of_care/diseases/_covid19_area_report.py#L22
if not, what will the new namespace be?

**Comment by tsolakoua** [comment]
Hello @siddydutta  :) That's a good question! 

We cannot replace yet the v1 implementation since there are users who still use v1. For the time being we will need to have both v1 and v2 in the SDK. 

As a new namespace, we would suggest `amadeus.duty_of_care.diseases.covid19_area_report`

**Comment by siddydutta** [comment]
Thank you for the answer @tsolakoua 
CMIIW `amadeus.duty_of_care.diseases.covid19_area_report` is the namespace for the existing v1 endpoint?

And yes, I am interested in contributing to this endpoint.

**Comment by tsolakoua** [comment]
Thanks @siddydutta  :) The v2 should be `amadeus.duty_of_care.diseases.covid19_report`, I made a mistake with copy/paste before
