### ISSUE TITLE
kids while looking for tickets

### ISSUE THREAD

**Issue by mrtineu** [amadeus4dev/amadeus-python#187]
HOw can i add kids when using amadeus.shopping.flight_offers_search

Thanks for any help

**Comment by siddydutta** [comment]
Hi @mrtineu This [API reference](https://developers.amadeus.com/self-service/category/air/api-doc/flight-offers-search/api-reference) might help.

**Comment by mrtineu** [comment]
> Hi @mrtineu This [API reference](https://developers.amadeus.com/self-service/category/air/api-doc/flight-offers-search/api-reference) might help.

So can i use it like this
try:
    response = amadeus.shopping.flight_offers_search.get(
        originLocationCode='BTS',
        destinationLocationCode='LHR',
        departureDate='2023-7-8',
        adults=89,
        child=3)
    print(response.data)
except ResponseError as error:
    print(error)

if not please write me example thanks

**Comment by siddydutta** [comment]
@mrtineu, replacing `child` with `children` should get you the desired result.
```python3
try:
    response = amadeus.shopping.flight_offers_search.get(
        originLocationCode='BTS', destinationLocationCode='LHR', departureDate='2023-07-08', adults=1, children=1)
    print(response.data)
except ResponseError as error:
    print(error)
```

**Comment by tsolakoua** [comment]
Thanks @siddydutta  :)
