### ISSUE TITLE
The errors aren't well formatted. And do not return json but html.  Secondly, adding nonStop parameter to the Flight Offer Search endpoint also throws errors.

### ISSUE THREAD

**Issue by Fidel-C** [amadeus4dev/amadeus-python#188]
## Description

[Describe the issue]

## Steps to Reproduce

1. [First step]
2. [Second step]
3. [and so on...]

__Expected Behavior:__ [What you expect to happen]

__Actual Behavior:__ [What actually happens]

__Stable Behavior?__ [What percentage of the time does it reproduce?]

## Versions

What version of Python/Pip are you running? What Operating System are you on?

## Checklist

Please make sure you checked the following:

* Which version of Python are you using?
* Did you download the latest version of this package?

**Comment by tsolakoua** [comment]
@Fidel-C As you can see the issue template is asking for some information such as the steps to reproduce it. Please add in the issue the information needed, especially the code snippet you have used so we will be able to investigate. Thanks!

**Comment by tsolakoua** [comment]
Closed due to lack of information to investigate
