### ISSUE TITLE
Filter flight offer search by date and time

### ISSUE THREAD

**Issue by sdelgadoc** [amadeus4dev/amadeus-python#194]
Is there a way to search for flights using date and time range? I am using the `flight_offers_search` function, but I can only search for all departures in a particular day.

The workaround I am going to implement is to run the time range filtering on the complete result set in my code, but if the API has the functionality built-in, I would rather use that.

Thanks for your help in advance! The toolkit is very helpful.

**Comment by minjikarin** [comment]
Hello @sdelgadoc, you are right, [Flight Offer Search API](https://developers.amadeus.com/self-service/category/flights/api-doc/flight-offers-search) is only to search with a specific date & time. in Amadeus Self-Service APIs, we don't have date range flight search available. if you are interested in more advanced functionalities in Flight search, I suggest you to consult to [Enterprise APIs](https://developers.amadeus.com/get-started/get-started-with-enterprise-apis-336). :)

**Comment by minjikarin** [comment]
by the way @sdelgadoc, I have seen your work on integrating Amadeus python SDK into Langchain agent toolkits. thank you so much for that. can I suggest to have a quick call with you to understand better on this ? and perhaps we can improve the Amadeus agent toolkit with more APIs available in the market to improve :) please, let me know your thoughts
