### ISSUE TITLE
Is there a field definition guide? Appreciated

### ISSUE THREAD

**Issue by yyz20002008** [amadeus4dev/amadeus-python#204]
I am using flight search API. just want to check if there is a value field definition guide. like what are different between "Prices" and "travelerPricings" ?
`
            "price": {
                "currency": "USD",
                "total": "2301.20",
                "base": "2010.00",
                "fees": [
                    {
                        "amount": "0.00",
                        "type": "SUPPLIER"
                    },
                    {
                        "amount": "0.00",
                        "type": "TICKETING"
                    }
                ],
                "grandTotal": "2301.20"
            },
          
            "travelerPricings": [
                {
                    "travelerId": "1",
                    "fareOption": "STANDARD",
                    "travelerType": "ADULT",
                    "price": {
                        "currency": "USD",
                        "total": "2301.20",
                        "base": "2010.00"
                    },
                    "fareDetailsBySegment": [
                        {
                            "segmentId": "1",
                            "cabin": "ECONOMY",
                            "fareBasis": "SFE0XSOS",
                            "brandedFare": "ECONOMY",
                            "class": "S",
                            "includedCheckedBags": {
                                "quantity": 1
                            }
                        }
                    ]
            ]
'

**Comment by yyz20002008** [comment]
And why lastticktingdate are different for same result.

`{
    "meta": {
        "count": 2,
        "links": {
            "self": "https://test.api.amadeus.com/v2/shopping/flight-offers?originLocationCode=SFO&destinationLocationCode=PVG&departureDate=2023-11-05&adults=1&nonStop=true&currencyCode=USD"
        }
    },
    "data": [
        {
            "type": "flight-offer",
            "id": "1",
            "source": "GDS",
            "instantTicketingRequired": false,
            "nonHomogeneous": false,
            "oneWay": false,
            "lastTicketingDate": "2023-10-01",
            "lastTicketingDateTime": "2023-10-01",
            "numberOfBookableSeats": 9,
            "itineraries": [
                {
                    "duration": "PT13H5M",
                    "segments": [
                        {
                            "departure": {
                                "iataCode": "SFO",
                                "terminal": "I",
                                "at": "2023-11-05T13:20:00"
                            },
                            "arrival": {
                                "iataCode": "PVG",
                                "terminal": "2",
                                "at": "2023-11-06T18:25:00"
                            },
                            "carrierCode": "UA",
                            "number": "857",
                            "aircraft": {
                                "code": "77W"
                            },
                            "operating": {
                                "carrierCode": "UA"
                            },
                            "duration": "PT13H5M",
                            "id": "1",
                            "numberOfStops": 0,
                            "blacklistedInEU": false
                        }
                    ]
                }
            ],
            "price": {
                "currency": "USD",
                "total": "2301.20",
                "base": "2010.00",
                "fees": [
                    {
                        "amount": "0.00",
                        "type": "SUPPLIER"
                    },
                    {
                        "amount": "0.00",
                        "type": "TICKETING"
                    }
                ],
                "grandTotal": "2301.20"
            },
            "pricingOptions": {
                "fareType": [
                    "PUBLISHED"
                ],
                "includedCheckedBagsOnly": true
            },
            "validatingAirlineCodes": [
                "UA"
            ],
            "travelerPricings": [
                {
                    "travelerId": "1",
                    "fareOption": "STANDARD",
                    "travelerType": "ADULT",
                    "price": {
                        "currency": "USD",
                        "total": "2301.20",
                        "base": "2010.00"
                    },
                    "fareDetailsBySegment": [
                        {
                            "segmentId": "1",
                            "cabin": "ECONOMY",
                            "fareBasis": "SFE0XSOS",
                            "brandedFare": "ECONOMY",
                            "class": "S",
                            "includedCheckedBags": {
                                "quantity": 1
                            }
                        }
                    ]
                }
            ]
        },
        {
            "type": "flight-offer",
            "id": "2",
            "source": "GDS",
            "instantTicketingRequired": false,
            "nonHomogeneous": false,
            "oneWay": false,
            "lastTicketingDate": "2023-10-08",
            "lastTicketingDateTime": "2023-10-08",
            "numberOfBookableSeats": 9,
            "itineraries": [
                {
                    "duration": "PT13H5M",
                    "segments": [
                        {
                            "departure": {
                                "iataCode": "SFO",
                                "terminal": "I",
                                "at": "2023-11-05T13:20:00"
                            },
                            "arrival": {
                                "iataCode": "PVG",
                                "terminal": "2",
                                "at": "2023-11-06T18:25:00"
                            },
                            "carrierCode": "CA",
                            "number": "7210",
                            "aircraft": {
                                "code": "77W"
                            },
                            "operating": {
                                "carrierCode": "UA"
                            },
                            "duration": "PT13H5M",
                            "id": "2",
                            "numberOfStops": 0,
                            "blacklistedInEU": false
                        }
                    ]
                }
            ],
            "price": {
                "currency": "USD",
                "total": "8698.20",
                "base": "8488.00",
                "fees": [
                    {
                        "amount": "0.00",
                        "type": "SUPPLIER"
                    },
                    {
                        "amount": "0.00",
                        "type": "TICKETING"
                    }
                ],
                "grandTotal": "8698.20"
            },
            "pricingOptions": {
                "fareType": [
                    "PUBLISHED"
                ],
                "includedCheckedBagsOnly": true
            },
            "validatingAirlineCodes": [
                "CA"
            ],
            "travelerPricings": [
                {
                    "travelerId": "1",
                    "fareOption": "STANDARD",
                    "travelerType": "ADULT",
                    "price": {
                        "currency": "USD",
                        "total": "8698.20",
                        "base": "8488.00"
                    },
                    "fareDetailsBySegment": [
                        {
                            "segmentId": "2",
                            "cabin": "ECONOMY",
                            "fareBasis": "YOFFUA",
                            "class": "Y",
                            "includedCheckedBags": {
                                "quantity": 2
                            }
                        }
                    ]
                }
            ]
        }
    ],
    "dictionaries": {
        "locations": {
            "PVG": {
                "cityCode": "SHA",
                "countryCode": "CN"
            },
            "SFO": {
                "cityCode": "SFO",
                "countryCode": "US"
            }
        },
        "aircraft": {
            "77W": "BOEING 777-300ER"
        },
        "currencies": {
            "USD": "US DOLLAR"
        },
        "carriers": {
            "UA": "UNITED AIRLINES",
            "CA": "AIR CHINA"
        }
    }
}`

**Comment by siddydutta** [comment]
You can check out the API Reference: [API Reference | Flight Offers Search API | Amadeus for Developers](https://developers.amadeus.com/self-service/category/flights/api-doc/flight-offers-search/api-reference).

![image](https://github.com/amadeus4dev/amadeus-python/assets/29818092/0dbe18a9-d9c1-49a0-85c4-af682ad53526)
