### ISSUE TITLE
Error code 2668 not returned with SDK, but works with curl request

### ISSUE THREAD

**Issue by fishforyou** [amadeus4dev/amadeus-python#206]
## Description

SDK fails to return error code and description. On top, documentation does not mention that 'alternativeOrigin/DestinationCodes are not combinable with timeWindow superior to 1D'.

## Steps to Reproduce

1. Send a POST request to flight-offers API with following body (e.g.):
{'currencyCode': 'USD',
 'originDestinations': [{'id': '1',
   'originLocationCode': 'ZRH',
   'destinationLocationCode': 'JFK',
   'departureDateTimeRange': {'date': '2024-02-01'}},
  {'id': '2',
   'originLocationCode': 'JFK',
   'destinationLocationCode': 'PTY',
   'departureDateTimeRange': {'date': '2024-02-05', 'dateWindow': 'I3D'},
   'alternativeDestinationsCodes': ['PUJ', 'HAV']}],
 'travelers': [{'id': '1', 'travelerType': 'ADULT'}],
 'sources': ['GDS'],
 'searchCriteria': {'maxFlightOffers': 250,
  'flightFilters': {'railSegmentAllowed': False,
   'cabinRestrictions': [{'cabin': 'ECONOMY',
     'coverage': 'MOST_SEGMENTS',
     'originDestinationIds': [1, 2]}]},
  'addOneWayFlightOffers': True}}

__Expected Behavior:__ 
Would expect this error message, as returned when using curl:
{'errors': [{'code': 2668,
   'title': 'PARAMETER COMBINATION INVALID/RESTRICTED',
   'detail': 'alternativeOrigin/DestinationCodes are not combinable with timeWindow superior to 1D',
   'status': 400}]}

__Actual Behavior:__
Instead a 400 error is returned without description. Some attributes are also missing, e.g. status_code

__Stable Behavior?__
It fails consistently

## Versions

What version of Python/Pip are you running? What Operating System are you on?
- python 3.9.12
- pip 23.3.1
- Darwin Kernel Version 23.1.0: RELEASE_ARM64_T8103
- Amadeus 9.0.0

## Checklist

Please make sure you checked the following:

* Which version of Python are you using?
* Did you download the latest version of this package?

**Comment by siddydutta** [comment]
Hi @fishforyou, not sure if this helps, but you can parse the error's response body.
```python3
try:
    response = amadeus.shopping.flight_offers_search.post(body)
except ClientError as err:
    response = json.loads(err.response.body)
    for error in response['errors']:
        print(error['code'])  # 2668
        print(error['title'])  # PARAMETER COMBINATION INVALID/RESTRICTED
        print(error['detail'])  # alternativeOrigin/DestinationCodes are not combinable with timeWindow superior to 1D
        print(error['status'])  # 400
```

**Comment by tsolakoua** [comment]
Thanks @siddydutta for your answer!
