### ISSUE TITLE
Query parameter 'scheduledDepartureDate' should not be past date

### ISSUE THREAD

**Issue by alexmellott** [amadeus4dev/amadeus-python#207]
## Description

Using the Production endpoint and a Python code sample, unable to return same-day flight information and receive the following error: `[scheduledDepartureDate] Query parameter 'scheduledDepartureDate' should not be past date`

## Steps to Reproduce

Sample Python code:
```
from amadeus import Client, ResponseError

amadeus = Client(
    client_id='<INSERT>',
    client_secret='<INSERT>',
    hostname='production'
)

try:
    '''
    Returns flight status of a given flight
    '''
    response = amadeus.schedule.flights.get(carrierCode='UA',
                                            flightNumber='1980',
                                            scheduledDepartureDate='2023-12-29')
    print(response.data)
except ResponseError as error:
    raise error
```

## Versions
Python3.11.5 MacOS 13.2.1

**Comment by tsolakoua** [comment]
Thanks @siddydutta for the answer. 

For future questions that are not related to the libraries, but are related to the API itself, get in touch with the dedicated [support channel](https://developers.amadeus.com/support).
