### ISSUE TITLE
"Your password must not contain more than 10 characters."

### ISSUE THREAD

**Issue by matkoniecz** [amadeus4dev/amadeus-python#21]
## Description

I know that it is a bit offtopic here, but I see no better place to report it.

https://developers.amadeus.com/create-account is extremely discouraging and suggests that Amadeus is not following best practices - at least in area of security.

"Your password must not contain more than 10 characters." is a quite absurd error message. Basic password security is that (a) passwords should be hashed, not stored as plaintext (b) passwords should be as long as possible.

## Steps to Reproduce

1. register at https://developers.amadeus.com/create-account as required in the readme
2. enter a password of a sensible length

__Expected Behavior: no problems

__Actual Behavior:__ "Your password must not contain more than 10 characters."

__Stable Behavior?__ 100%

**Comment by matkoniecz** [comment]
I now send it also to https://developers.amadeus.com/support/contact-us-self-service/message

**Comment by anthonyroux** [comment]
Thanks for the feedback.

Fixed
