### ISSUE TITLE
amadeus.shopping.flight_destinations.get(origin='LHR') causes server error

### ISSUE THREAD

**Issue by matkoniecz** [amadeus4dev/amadeus-python#26]
## Description

Attempting to run code from documentation ( https://amadeus4dev.github.io/amadeus-python/#shopping-flights )  fails

## Steps to Reproduce

1. Run

```
from amadeus import Client, ResponseError

amadeus = Client(
    client_id='<SNIP>',
    client_secret='<SNIP>'
)



try:
    response = amadeus.shopping.flight_destinations.get(origin='LHR')
    print(response.data)
    print(response.result)
    print(response.body)
    print(response)
except ResponseError as error:
    print("Error")
    print(error)
    print(error.code)
```

__Expected Behavior:__ [What you expect to happen]

Code based on https://amadeus4dev.github.io/amadeus-python/#shopping-flights and readme will work

__Actual Behavior:__ [What actually happens]

```
Error
[500]

ServerError
```

__Stable Behavior?__ [What percentage of the time does it reproduce?]

Today it is stable, 100% reproducibility.

## Versions

(not filled as based on #21 it seems that it will be ignored anyway - if any human is reading this please let me known and I will finish report)

What version of Python/Pip are you running? What Operating System are you on?

## Checklist

Please make sure you checked the following:

* Are you running Python 2.7 or 3.6?
* Did you download the latest version of this package?

**Comment by anthonyroux** [comment]
Hi,

The dataset we have in the test environment is limited, LHR is not part of it.
You can find the list of origins and destinations supported for this API [here](https://github.com/amadeus4dev/hackathon-starter/blob/master/datasets/flightsearch.md)

We have 2 things on going on our side to improve it:
- Offering a smarter dataset in test
- Publishing the list of origins and destinations on the portal for more clarity

Thanks for reporting it I have updated the python doc to put an example that works.
You can try with LON for example.

Cheers,
Anthony
