### ISSUE TITLE
Is it supported for Enterprise APIs (SOAP, XML,HEADER 4.0 )  with state full & state less session handling ?

### ISSUE THREAD

**Issue by ketan0777** [amadeus4dev/amadeus-python#32]
Is it supported for Enterprise APIs (SOAP, XML,HEADER 4.0 ) ?

**Comment by alnacle** [comment]
Hello! The SDK supports only Amadeus Self-service REST/JSON APIs. Please take a look to our Self-Service [Get started guide](https://developers.amadeus.com/quick-start-guide/category?id=77&durl=335&parentId=NaN). Thanks!

**Comment by ketan0777** [comment]
Is It new implementation From AMADEUS to support REST/JSON API? 

because I had worked on SOAP base web service
