### ISSUE TITLE
Python 3.5 or lower: example throws exception despite 200 status response

### ISSUE THREAD

**Issue by samheyman** [amadeus4dev/amadeus-python#4]
## Description

When running the example given in the Getting Started section, the response status is 200 but an exception is thrown. The user just sees: Error: Status 200 []

## Steps to Reproduce

1. Copy example from Getting started
2. Run with python 3.5 (or lower)
3. Verify exception thrown despite 200 status response

__Expected Behavior:__ with python 3.6 you get an array of airline check-in urls

## Versions

Python 3.5 

## Checklist

Please make sure you checked the following:

* Are you running Python 2.7 or 3.6?
* Did you download the latest version of this package?

**Comment by samheyman** [comment]
One possible solution is to decode the response as utf-8. One team found that this fixed the issue for them.

**Comment by cbetta** [comment]
Looking into this now
