### ISSUE TITLE
AttributeError for flight_offers_search

### ISSUE THREAD

**Issue by ansin218** [amadeus4dev/amadeus-python#91]
I have been trying to migrate from **_Flight Low-fare Search_** to _**Flight Offers Search**_. 

On running the following block of code from the examples:
```
try:
    '''
    Find the cheapest flights from SYD to BKK
    '''
    response = amadeus.shopping.flight_offers_search.get(originLocationCode='SYD', destinationLocationCode='BKK', departureDate='2020-07-01', adults=1)
    # print(response.data)
except ResponseError as error:
    raise error
```
I get:
```
Traceback (most recent call last):

  File "<ipython-input-7-ee2011bb3023>", line 5, in <module>
    response = amadeus.shopping.flight_offers_search.get(originLocationCode='SYD', destinationLocationCode='BKK', departureDate='2020-07-01', adults=1)

AttributeError: 'Shopping' object has no attribute 'flight_offers_search'
```
I have been running the old API, that is to be decommissioned, successfully for almost six months now without any issues. Can someone please help me here with the new API?

**Comment by alnacle** [comment]
Make sure you have updated to the latest version of the package (4.0.0):

`pip install --upgrade amadeus`

Hope it helps!

**Comment by ansin218** [comment]
That was a really simple fix. My bad. 

Thanks a ton!
