### ISSUE TITLE
Flight Search Returns airline codes 6X and 7X

### ISSUE THREAD

**Issue by dev10110** [amadeus4dev/amadeus-python#97]
## Description

Performing a flight search between SIN and LHR, in the returned results I can see that some of the shortest flight time results are from carrier code "6X" and "7X" which the dictionary claims is 'Amadeus Six' and 'Amadeus Seven". 

I am unsure what these airlines refer to, and whether this is only the case for the testing data set. 
 
## Steps to Reproduce

`
response = amadeus.shopping.flight_offers_search.get(
                originLocationCode="SIN",
                destinationLocationCode="LHR",
                departureDate="2021-02-01",
                adults=1)
`

__Expected Behavior:__ 

Carrier codes do not represent fictional airlines.

__Actual Behavior:__ 
Carrier codes include "6X" and "7X"

__Stable Behavior?__ 
Seems to be. 

## Versions

Mac OS, Python 3.8.

**Comment by tsolakoua** [comment]
Hello @dev10110, the test environment contains data that are cached or can be dummy data as well. So this behavior is normal for the test environment of the Flight Offers Search API. The production environment instead contains only real live data.
